
version: '3.7'

services:
  database:
    image: mysql:latest
    container_name: wordpress-db
    hostname: wordpress-db
    volumes:
      - wp-db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: wordpress
      # MYSQL_USER: wp
      # MYSQL_PASSWORD: P@ssw0rd
    networks:
      - backend

  wordpress:
    depends_on:
    - database
    image: wordpress:latest
    container_name: wordpress
    hostname: wordpress-xtra
    volumes:
      - wp-site-data:/var/www/html
    ports:
    - "${WPIP}:8090:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: P@ssw0rd
    networks:
      - backend

  adminer:
    depends_on:
    - database
    image: adminer
    container_name: wp-adminer
    hostname: wp-adminer
    restart: always
    ports:
      - ${WPIP}:8080:8080
    networks:
      - backend

networks:
  backend:
    name: wp-net

volumes:
  wp-db-data:
    external: true
  wp-site-data:
    external: true

